language: node_js
node_js: 9
if: tag IS blank
script:
  - npm install -g npm
  - npm install
  - rm -r dist
  - npm run build:prod
  - ls
  - ls dist
  - cd dist
  - echo abc > abc.txt
  - cd ..
  - ls dist
  - zip -r dist.zip dist
before_deploy:
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: gobblydigook
  file: dist.zip
  skip_cleanup: true
  on:
    repo: dhinakg/gdrive-copy
    
